version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A myproject worker --loglevel=info
    depends_on:
      - redis
